spring.config.import=classpath:secrets.properties

pring.application.name=brief-business

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Server Configuration
server.port=${SERVER_PORT}

# JPA Configuration
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.root=${LOGGING_LEVEL_ROOT}
logging.level.co.simplon=${LOGGING_LEVEL_CO_SIMPLON}
